spring:
  application:
    name: lawgg-content
  config:
#    import: optional:configserver:http://spring-cloud-config:8888/ # spring cloud config ?? ?? (?? ?? option ??)
    import: optional:configserver:http://192.168.0.3:8888/ # spring cloud config ?? ?? (?? ?? option ??)
  profiles:
    active: local
    group:
      local:
        - console-logging # ?? ??? ??
      test:
        - console-logging
        - file-logging # ?? ?? ??
      prod:
        - console-logging
        - file-logging # ?? ?? ??
  kafka:
    producer:
      properties:
        min:
          insync:
            replicas: 2

kafka:
  bootstrapAddress: 192.168.0.3:6687
  admin:
    properties:
  topic:
    alarm:
      name: lawgg-alert
      replicationFactor: 1
      numPartitions: 1
  consumer:
    alarm:
      rdb-group-id: createAlarmInRDB
      redis-group-id: publishInRedis
    autoOffsetResetConfig: latest
  producer:
    acksConfig: all
    retry: 3
    enable-idempotence: true
    max-in-flight-requests-per-connection: 3