spring:
  application:
    name: lawgg-content
  config:
#    import: optional:configserver:http://spring-cloud-config:8888/ # spring cloud config
    import: optional:configserver:http://192.168.0.3:8888/ # spring cloud config
  profiles:
    active: local
    group:
      local:
        - console-logging
      test:
        - console-logging
        - file-logging
      prod:
        - console-logging
        - file-logging